# rag/hyde.py
"""
HyDE (Hypothetical Document Embeddings) - search execution using a
hypothetical document's embedding to bridge the semantic gap between short
queries and long documents.

Reference: Gao et al. "Precise Zero-Shot Dense Retrieval without Relevance Labels" (2023)

Note: the hypothetical document itself is now generated by
ai.query_enhancer.analyze_query_with_context() in the same structured call
as query rewriting (C3 in SPEC.md) -- this module previously had its own
generate_hypothetical_document() with a separate LLM call, which is now
redundant and has been removed.
"""


def hyde_search(hyde_doc: str,
                search_fn,
                k: int = 10) -> list:
    """
    Perform HyDE-enhanced search: retrieve using the hypothetical document's
    embedding, which sits closer to real document embeddings than the short
    original query does.

    Note: this does NOT also search the original query — retrieve_node's main
    path (process_with_rag_detailed) already does that with the same
    underlying function. Searching it again here was pure duplicate work
    whose results were mostly discarded at the final content-based dedupe
    anyway.

    Args:
        hyde_doc: Generated hypothetical document
        search_fn: Function that takes (query, k) and returns list of documents
        k: Number of results to retrieve

    Returns:
        Deduplicated list of documents from the HyDE search
    """
    hyde_results = search_fn(hyde_doc, k=k)

    # Deduplicate by content prefix (search_fn can return overlapping chunks)
    seen = set()
    merged = []
    for doc in hyde_results:
        content = doc.page_content if hasattr(doc, 'page_content') else str(doc)
        key = content[:150]
        if key not in seen:
            seen.add(key)
            merged.append(doc)

    print(f"[HyDE] HyDE search returned {len(hyde_results)} results, {len(merged)} unique")
    return merged
